name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Exercise1Test
      id: exercise1test
      uses: education/autograding-command-grader@v1
      with:
        test-name: Exercise1Test
        setup-command: sudo -H pip3 install pytest
        command: pytest aufgabe1_test.py
        timeout: 10
        max-score: 10
    - name: Exercise3Test
      id: exercise3test
      uses: education/autograding-command-grader@v1
      with:
        test-name: Exercise3Test
        setup-command: sudo -H pip3 install pytest
        command: pytest aufgabe3_test.py
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        EXERCISE1TEST_RESULTS: "${{steps.exercise1test.outputs.result}}"
        EXERCISE3TEST_RESULTS: "${{steps.exercise3test.outputs.result}}"
      with:
        runners: exercise1test,exercise3test
